#!/usr/bin/env bash
# Synthetic-only. Compose project/ports are fixed and never refer to local or production Mongo.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"; SELF="$ROOT/scripts/mongo-consolidation/target-sandbox"; RUN="$SELF/runtime"; PROJECT=sitebuilder-mongo-target-sandbox
C=(docker compose --project-name "$PROJECT" --env-file "$RUN/compose.env" -f "$SELF/compose.yml")
B=(docker compose --project-name "$PROJECT" --env-file "$RUN/compose.env" -f "$SELF/compose.yml" -f "$SELF/compose.bootstrap.yml")
m(){ "${C[@]}" exec -T mongo-sandbox-1 mongosh 'mongodb://mongo-sandbox-1:27017,mongo-sandbox-2:27017,mongo-sandbox-3:27017/admin?replicaSet=sbSandboxRs' --quiet --tls --tlsCAFile /run/s/ca.pem --tlsCertificateKeyFile /run/s/mongo-sandbox-1.pem "$@"; }
root(){ m -u sandbox_root -p sandbox-root-only --authenticationDatabase admin "$@"; }
prep(){ command -v docker >/dev/null; command -v openssl >/dev/null; mkdir -p "$RUN/certs" "$SELF/reports" "$SELF/backups"; umask 077; openssl rand -base64 756 > "$RUN/certs/keyfile"; chmod 400 "$RUN/certs/keyfile"; openssl req -x509 -newkey rsa:2048 -nodes -days 7 -subj /CN=sb-ca -keyout "$RUN/certs/ca-key.pem" -out "$RUN/certs/ca.pem" >/dev/null 2>&1; for n in 1 2 3; do h=mongo-sandbox-$n; openssl req -newkey rsa:2048 -nodes -subj "/CN=$h" -keyout "$RUN/certs/$h-key.pem" -out "$RUN/certs/$h.csr" >/dev/null 2>&1; printf 'subjectAltName=DNS:%s\n' "$h" > "$RUN/certs/$h.ext"; openssl x509 -req -days 7 -CA "$RUN/certs/ca.pem" -CAkey "$RUN/certs/ca-key.pem" -CAcreateserial -in "$RUN/certs/$h.csr" -out "$RUN/certs/$h-cert.pem" -extfile "$RUN/certs/$h.ext" >/dev/null 2>&1; cat "$RUN/certs/$h-key.pem" "$RUN/certs/$h-cert.pem" > "$RUN/certs/$h.pem"; chmod 400 "$RUN/certs/$h.pem"; done; printf 'SANDBOX_PROJECT=%s\nSANDBOX_RUNTIME=%s\nSANDBOX_PORT_1=27171\nSANDBOX_PORT_2=27172\nSANDBOX_PORT_3=27173\n' "$PROJECT" "$RUN" > "$RUN/compose.env"; }
up(){ prep; "${B[@]}" up -d --wait; until m --eval 'db.adminCommand({ping:1})' >/dev/null 2>&1; do sleep 1; done; m --eval 'rs.initiate({_id:"sbSandboxRs",members:[{_id:0,host:"mongo-sandbox-1:27017"},{_id:1,host:"mongo-sandbox-2:27017"},{_id:2,host:"mongo-sandbox-3:27017"}]})'; until m --eval 'let s=rs.status();if(s.members.filter(x=>x.stateStr=="PRIMARY").length!=1||s.members.filter(x=>x.stateStr=="SECONDARY").length!=2)quit(1)';do sleep 2;done; m --eval 'db.getSiblingDB("admin").createUser({user:"sandbox_root",pwd:"sandbox-root-only",roles:["root"]})'; m --eval 'let a=db.getSiblingDB("admin");a.createUser({user:"hub_control_app",pwd:"hub-control-only",roles:[{role:"readWrite",db:"sitebuilder_hub"}]});a.createUser({user:"hub_site_data_app",pwd:"hub-data-only",roles:[{role:"readWrite",db:"sitebuilder_site_data"}]});a.createUser({user:"hub_auditor",pwd:"hub-auditor-only",roles:[{role:"readAnyDatabase",db:"admin"}]});a.createUser({user:"hub_backup",pwd:"hub-backup-only",roles:[{role:"backup",db:"admin"},{role:"restore",db:"admin"}]})'; "${B[@]}" down; "${C[@]}" up -d --wait; until root --eval 'db.adminCommand({ping:1})' >/dev/null 2>&1; do sleep 1; done; }
test(){ docker cp "$SELF/seed-and-test.mjs" mongo-sandbox-1:/tmp/t.mjs; root --file /tmp/t.mjs | tee "$SELF/reports/sandbox-test.log"; }
down(){ [ -f "$RUN/compose.env" ] && "${C[@]}" down --remove-orphans || true; }
destroy(){ down; [ -f "$RUN/compose.env" ] && "${C[@]}" down --volumes --remove-orphans || true; find "$RUN" "$SELF/reports" "$SELF/backups" -mindepth 1 -delete 2>/dev/null || true; }
case "${1:-}" in up)up;;test)test;;down)down;;destroy)destroy;;*)echo 'usage: sandbox.sh {up|test|down|destroy}'>&2;exit 2;;esac
