#!/usr/bin/env bash
# Synthetic-only. Compose project/ports are fixed and never refer to local or production Mongo.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"; SELF="$ROOT/scripts/mongo-consolidation/target-sandbox"; RUN="$SELF/runtime"; PROJECT=sitebuilder-mongo-target-sandbox
C=(docker compose --project-name "$PROJECT" --env-file "$RUN/compose.env" -f "$SELF/compose.yml")
B=(docker compose --project-name "$PROJECT" --env-file "$RUN/compose.env" -f "$SELF/compose.yml" -f "$SELF/compose.bootstrap.yml")
m(){ "${C[@]}" exec -T mongo-sandbox-1 mongosh 'mongodb://mongo-sandbox-1:27017,mongo-sandbox-2:27017,mongo-sandbox-3:27017/admin?replicaSet=sbSandboxRs' --quiet --tls --tlsCAFile /run/s/ca.pem --tlsCertificateKeyFile /run/s/mongo-sandbox-1.pem "$@"; }
bm(){ "${B[@]}" exec -T mongo-sandbox-1 mongosh 'mongodb://mongo-sandbox-1:27017/admin?directConnection=true' --quiet --tls --tlsCAFile /run/s/ca.pem --tlsCertificateKeyFile /run/s/mongo-sandbox-1.pem "$@"; }
root(){ m -u sandbox_root -p sandbox-root-only --authenticationDatabase admin "$@"; }
prep(){ command -v docker >/dev/null; command -v openssl >/dev/null; mkdir -p "$RUN/certs" "$SELF/reports" "$SELF/backups"; chmod u+w "$RUN/certs"/* 2>/dev/null || true; umask 077; openssl rand -base64 756 > "$RUN/certs/keyfile"; chmod 400 "$RUN/certs/keyfile"; openssl req -x509 -newkey rsa:2048 -nodes -days 7 -subj /CN=sb-ca -keyout "$RUN/certs/ca-key.pem" -out "$RUN/certs/ca.pem" >/dev/null 2>&1; for n in 1 2 3; do h=mongo-sandbox-$n; openssl req -newkey rsa:2048 -nodes -subj "/CN=$h" -keyout "$RUN/certs/$h-key.pem" -out "$RUN/certs/$h.csr" >/dev/null 2>&1; printf 'subjectAltName=DNS:%s\n' "$h" > "$RUN/certs/$h.ext"; openssl x509 -req -days 7 -CA "$RUN/certs/ca.pem" -CAkey "$RUN/certs/ca-key.pem" -CAcreateserial -in "$RUN/certs/$h.csr" -out "$RUN/certs/$h-cert.pem" -extfile "$RUN/certs/$h.ext" >/dev/null 2>&1; cat "$RUN/certs/$h-key.pem" "$RUN/certs/$h-cert.pem" > "$RUN/certs/$h.pem"; chmod 400 "$RUN/certs/$h.pem"; done; printf 'SANDBOX_PROJECT=%s\nSANDBOX_RUNTIME=%s\nSANDBOX_PORT_1=27171\nSANDBOX_PORT_2=27172\nSANDBOX_PORT_3=27173\n' "$PROJECT" "$RUN" > "$RUN/compose.env"; }
up(){ prep; "${B[@]}" up -d --wait; until bm --eval 'db.adminCommand({ping:1})' >/dev/null 2>&1; do sleep 1; done; bm --eval 'rs.initiate({_id:"sbSandboxRs",members:[{_id:0,host:"mongo-sandbox-1:27017"},{_id:1,host:"mongo-sandbox-2:27017"},{_id:2,host:"mongo-sandbox-3:27017"}]})'; until bm --eval 'let s=rs.status();if(s.members.filter(x=>x.stateStr=="PRIMARY").length!=1||s.members.filter(x=>x.stateStr=="SECONDARY").length!=2)quit(1)';do sleep 2;done; m --eval 'db.getSiblingDB("admin").createUser({user:"sandbox_root",pwd:"sandbox-root-only",roles:["root"]})'; m --eval 'let a=db.getSiblingDB("admin");a.createUser({user:"hub_control_app",pwd:"hub-control-only",roles:[{role:"readWrite",db:"sitebuilder_hub"}]});a.createUser({user:"hub_site_data_app",pwd:"hub-data-only",roles:[{role:"readWrite",db:"sitebuilder_site_data"}]});a.createUser({user:"hub_auditor",pwd:"hub-auditor-only",roles:[{role:"readAnyDatabase",db:"admin"}]});a.createUser({user:"hub_backup",pwd:"hub-backup-only",roles:[{role:"backup",db:"admin"},{role:"restore",db:"admin"}]})'; "${B[@]}" down; "${C[@]}" up -d --wait; until root --eval 'db.adminCommand({ping:1})' >/dev/null 2>&1; do sleep 1; done; }
expect_denied(){ if "$@" >/dev/null 2>&1; then echo "expected denial succeeded" >&2; return 1; fi; }
test(){
  root --eval 'db.getSiblingDB("sitebuilder_hub").sites.insertOne({siteCode:"SYN-EXACT",builderSiteId:"builder-exact"});db.getSiblingDB("sitebuilder_site_data").sites.insertOne({siteId:"builder-exact",safeCollectionName:"site_builder_exact"});db.getSiblingDB("sitebuilder_site_data").createCollection("site_builder_exact");db.getSiblingDB("sitebuilder_site_data").site_builder_exact.createIndex({siteId:1,scope:1});db.getSiblingDB("sitebuilder_site_data").site_builder_exact.insertOne({siteId:"builder-exact",scope:"default",version:1});print("SEED_OK")'
  m -u hub_control_app -p hub-control-only --authenticationDatabase admin --eval 'db.getSiblingDB("sitebuilder_hub").getCollection("probe").insertOne({ok:true});print("CONTROL_ALLOW")'
  expect_denied m -u hub_control_app -p hub-control-only --authenticationDatabase admin --eval 'db.getSiblingDB("sitebuilder_site_data").getCollection("probe").insertOne({mustFail:true})'
  m -u hub_site_data_app -p hub-data-only --authenticationDatabase admin --eval 'db.getSiblingDB("sitebuilder_site_data").getCollection("probe").insertOne({ok:true});print("DATA_ALLOW")'
  expect_denied m -u hub_site_data_app -p hub-data-only --authenticationDatabase admin --eval 'db.getSiblingDB("sitebuilder_hub").getCollection("probe").insertOne({mustFail:true})'
  m -u hub_auditor -p hub-auditor-only --authenticationDatabase admin --eval 'db.getSiblingDB("sitebuilder_hub").sites.findOne();db.getSiblingDB("sitebuilder_site_data").sites.findOne();print("AUDITOR_READ_ALLOW")'
  expect_denied m -u hub_auditor -p hub-auditor-only --authenticationDatabase admin --eval 'db.getSiblingDB("sitebuilder_hub").getCollection("probe").insertOne({mustFail:true})'
  root --eval 'const s=db.getMongo().startSession();const d=s.getDatabase("sitebuilder_site_data");s.startTransaction({writeConcern:{w:"majority"}});d.revisions.insertOne({siteId:"builder-exact",version:2});d.site_builder_exact.insertOne({siteId:"builder-exact",scope:"tx"});d.sites.updateOne({siteId:"builder-exact"},{$set:{touched:true}});d.site_data_audit.insertOne({siteId:"builder-exact",event:"tx"});s.commitTransaction();s.startTransaction();d.revisions.insertOne({version:999});s.abortTransaction();if(db.getSiblingDB("sitebuilder_site_data").revisions.countDocuments({version:999}))throw Error("rollback failed");print("TRANSACTION_OK")'
  root --eval 'const s=rs.status();if(s.members.filter(x=>x.stateStr==="PRIMARY").length!==1||s.members.filter(x=>x.stateStr==="SECONDARY").length!==2)throw Error("unexpected replica state");print("REPLICA_HEALTH_OK")' | tee "$SELF/reports/sandbox-test.log"
  grep -qx 'REPLICA_HEALTH_OK' "$SELF/reports/sandbox-test.log"
}
down(){ [ -f "$RUN/compose.env" ] && "${C[@]}" down --remove-orphans || true; }
destroy(){ down; [ -f "$RUN/compose.env" ] && "${C[@]}" down --volumes --remove-orphans || true; find "$RUN" "$SELF/reports" "$SELF/backups" -mindepth 1 -delete 2>/dev/null || true; }
case "${1:-}" in up)up;;test)test;;down)down;;destroy)destroy;;*)echo 'usage: sandbox.sh {up|test|down|destroy}'>&2;exit 2;;esac
